name: makemeadrink
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.0

  user_repository: 
    path: packages/user_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icona_app.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/json/cocktails.json
    - assets/images/icon_list.png
    - assets/images/cocktail_favorites_icon.png
    - assets/images/startScreenImage.png
    - assets/images/icona_app.png
