// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWkvrn9IumnVgTZD72fv1BZogohlQdbs',
    appId: '1:134000251102:web:e3222943f0939a44ee724f',
    messagingSenderId: '134000251102',
    projectId: 'makemeadrink-c19cd',
    authDomain: 'makemeadrink-c19cd.firebaseapp.com',
    storageBucket: 'makemeadrink-c19cd.firebasestorage.app',
    measurementId: 'G-KWRSZR68KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PWuC01J3py2IP5704MGGK-YB7HAF-Bk',
    appId: '1:134000251102:android:9c657b613bb45753ee724f',
    messagingSenderId: '134000251102',
    projectId: 'makemeadrink-c19cd',
    storageBucket: 'makemeadrink-c19cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh46fACPa6K1Ll2zCCfPLuS86r3jAMxis',
    appId: '1:134000251102:ios:79f8afe68260fd3aee724f',
    messagingSenderId: '134000251102',
    projectId: 'makemeadrink-c19cd',
    storageBucket: 'makemeadrink-c19cd.firebasestorage.app',
    iosBundleId: 'com.example.makemeadrink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh46fACPa6K1Ll2zCCfPLuS86r3jAMxis',
    appId: '1:134000251102:ios:79f8afe68260fd3aee724f',
    messagingSenderId: '134000251102',
    projectId: 'makemeadrink-c19cd',
    storageBucket: 'makemeadrink-c19cd.firebasestorage.app',
    iosBundleId: 'com.example.makemeadrink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUWkvrn9IumnVgTZD72fv1BZogohlQdbs',
    appId: '1:134000251102:web:371229a7c52cd005ee724f',
    messagingSenderId: '134000251102',
    projectId: 'makemeadrink-c19cd',
    authDomain: 'makemeadrink-c19cd.firebaseapp.com',
    storageBucket: 'makemeadrink-c19cd.firebasestorage.app',
    measurementId: 'G-ZMN6RS0MHL',
  );
}
